### ISSUE TITLE
Hide animation only plays for name plate, not image

### ISSUE THREAD

**Issue by Janonas** [sanguaire/portrait-box#4]
When you no longer hover on a token, its portrait dissapears instantly while only its name plate plays the animation.

**Comment by Janonas** [comment]
Additionally, when changing animation is neccesary for the fix of issue 3 to work, though its not that big of a deal.

**Comment by sanguaire** [comment]
I guess only changing is nessesary. Can you check it?

**Comment by Janonas** [comment]
Yes, changing makes the module functions close to intendet, however, no matter what, the hide animation only affectsthe nameplate, the image dissapears instantly once you stop howering, playing no animation.

**Comment by sanguaire** [comment]
fixed in version v0.4.5
