### ISSUE TITLE
[Feature Request] Disable Portrait Box for Specific Tokens

### ISSUE THREAD

**Issue by ViridiumRP** [sanguaire/portrait-box#9]
Hey there! Huge fan of your module! I often times want to either hide a token or wait to display portrait art. Would it be possible to maybe add a toggle on a per token basis? Maybe in the token settings? Thanks again for your awesome module!

**Comment by sanguaire** [comment]
The feature is already in this module but not documented 😊

You can set a flag on the token with this makro

```
if(canvas.tokens.controlled.length === 0) 
    return;

canvas.tokens.controlled.forEach(async t => 
    await t.document.setFlag('portrait-box', 'disabled', 
                     !t.document.getFlag('portrait-box', 'disabled')));
```
